{application,nitrogen,
             [{description,"akb.io blog"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[about,aroundtheweb,common,contact,element_test,index,
                        mailing_list,meetings,members,mobile,nitrogen_app,
                        nitrogen_inets,nitrogen_sup,tutorials,xmpp]}]}.
